'use client'; // Keep if you need client-side interactions, otherwise remove for static rendering

import React from 'react';
import styles from './page.module.css';
import Link from 'next/link';

const TermsPage = () => {
    return (
        <div className={styles.pageContainer}>
            <header className={styles.header}>
                <h1>Terms and Conditions</h1>
                <p>Last Updated: {new Date().toLocaleDateString()}</p>
            </header>

            <section className={styles.contentSection}>
                <h2>1. Introduction</h2>
                <p>
                    Welcome to The Future Classroom ("Platform", "Service"). These Terms and Conditions ("Terms") govern your use of our website located at [Your Website URL] and our services.
                    By accessing or using the Service, you agree to be bound by these Terms. If you disagree with any part of the terms, then you may not access the Service.
                </p>

                <h2>2. Use License</h2>
                <p>
                    Permission is granted to temporarily download one copy of the materials (information or software) on The Future Classroom's website for personal, non-commercial transitory viewing only. This is the grant of a license, not a transfer of title, and under this license you may not:
                </p>
                <ul>
                    <li>modify or copy the materials;</li>
                    <li>use the materials for any commercial purpose, or for any public display (commercial or non-commercial);</li>
                    <li>attempt to decompile or reverse engineer any software contained on The Future Classroom's website;</li>
                    <li>remove any copyright or other proprietary notations from the materials; or</li>
                    <li>transfer the materials to another person or "mirror" the materials on any other server.</li>
                </ul>
                <p>
                    This license shall automatically terminate if you violate any of these restrictions and may be terminated by The Future Classroom at any time. Upon terminating your viewing of these materials or upon the termination of this license, you must destroy any downloaded materials in your possession whether in electronic or printed format.
                </p>

                <h2>3. AI Tool Usage</h2>
                <p>
                    The AI tools provided on this Platform are for educational assistance and informational purposes only. While we strive for accuracy, the output generated by AI may contain errors, inaccuracies, or biases. Users are solely responsible for evaluating the accuracy, appropriateness, and usefulness of any information generated by the AI tools.
                </p>
                <p>
                    You agree not to use the AI tools for any purpose that is unlawful, harmful, or violates the rights of others. You must ensure you have the necessary rights and permissions for any content you input into the AI tools (e.g., uploading textbooks).
                </p>
                <p>
                    The Future Classroom makes no warranties regarding the reliability, accuracy, or completeness of the AI-generated content. Use the AI tools at your own risk and always apply professional judgment.
                </p>

                <h2>4. Disclaimer</h2>
                <p>
                    The materials on The Future Classroom's website are provided on an 'as is' basis. The Future Classroom makes no warranties, expressed or implied, and hereby disclaims and negates all other warranties including, without limitation, implied warranties or conditions of merchantability, fitness for a particular purpose, or non-infringement of intellectual property or other violation of rights.
                </p>
                {/* Add more sections as needed: Limitations, Revisions, Links, Governing Law, User Accounts, Content Ownership, etc. */}
                <p>...</p>

                <h2>5. Governing Law</h2>
                <p>
                    These terms and conditions are governed by and construed in accordance with the laws of [Your Jurisdiction, e.g., India] and you irrevocably submit to the exclusive jurisdiction of the courts in that State or location.
                </p>

                <h2>6. Changes to Terms</h2>
                <p>
                    The Future Classroom reserves the right to revise these Terms at any time without notice. By using this website you are agreeing to be bound by the then current version of these Terms and Conditions.
                </p>

                <h2>7. Contact Us</h2>
                <p>
                    If you have any questions about these Terms, please contact us at [Your Contact Email or Link].
                </p>
            </section>
        </div>
    );
};

export default TermsPage; 